### PR TITLE
Perf/simd base64

### PR DESCRIPTION
**Pull request by IWANABETHATGUY**

### CODE REVIEW

**Comment by h-a-n-a** [comment]
> Don't merge, let's add some benchmark first. In theory, this would be faster

Tested locally, `base64_simd` is even slower than `base64` by around 30ms in react example with release profile enabled.

**Comment by IWANABETHATGUY** [comment]
It doesn't make sense. https://github.com/Nugine/simd/blob/main/docs/benches-v050.md

**Comment by IWANABETHATGUY** [comment]
```bash
base64-simd:
test benchmark_concat_generate_base64            ... bench:   2,545,590 ns/iter (+/- 78,112)
test benchmark_concat_generate_base64_with_cache ... bench:   1,696,344 ns/iter (+/- 114,908)
test benchmark_concat_generate_string            ... bench:   2,506,639 ns/iter (+/- 120,088)
test benchmark_concat_generate_string_with_cache ... bench:   1,649,825 ns/iter (+/- 60,293)
test benchmark_concat_generate_url               ... bench:   2,548,261 ns/iter (+/- 100,481)
test benchmark_concat_generate_url_with_cache    ... bench:   1,705,380 ns/iter (+/- 83,842)

base-64:

test benchmark_concat_generate_base64            ... bench:   2,769,423 ns/iter (+/- 396,494)
test benchmark_concat_generate_base64_with_cache ... bench:   1,841,818 ns/iter (+/- 257,192)
test benchmark_concat_generate_string            ... bench:   2,478,724 ns/iter (+/- 337,036)
test benchmark_concat_generate_string_with_cache ... bench:   1,648,572 ns/iter (+/- 70,154)
test benchmark_concat_generate_url               ... bench:   2,661,842 ns/iter (+/- 266,013)
test benchmark_concat_generate_url_with_cache    ... bench:   1,799,586 ns/iter (+/- 462,726)
```

**Comment by IWANABETHATGUY** [comment]
the bench result only change the two comment status of `base64` and `base64_simd` https://github.com/speedy-js/rspack-sources/pull/1/files#diff-39d3bd8efc211d999c40815f20eebe6132af038f995096b6ca3cf6b0a3fa9683R86-R87

**Comment by h-a-n-a** [comment]
Looks like CI failed, we can disable node benchmarks for now

**Comment by IWANABETHATGUY** [comment]
Would reopen another pr

**Pull request closed without merging**
